### ISSUE TITLE
Problem while importing Accelerated Text into Reaction Commerce

### ISSUE THREAD

**Issue by mikecheng-super-chain** [tokenmill/reaction-acc-text-demo#2]
I am trying to import Accelerated Text into Reaction Commerce just as the reaction-acc-text-demo does.
But I constantly get errors similar to the following when I am trying to run "make run" under the terminal, which is following the first step:
(base) UserName$ make run
(git submodule update --remote && git pull --recurse-submodules)
error: Your local changes to the following files would be overwritten by checkout:
api/resources/paradigms/eng/AdV.edn
api/resources/paradigms/est/AdV.edn
api/resources/paradigms/spa/AdV.edn
api/resources/syntax/AdV.edn
Please commit your changes or stash them before you switch branches.
Aborting
Unable to checkout '5a76c25b9d3ecccf6eabf2ab2eeeb8733dfbe7ca' in submodule path 'accelerated-text'
make: * [pull-submodules] Error 1

**Comment by zaibacu** [comment]
Ok, thank you for info. It's problem from our side, mostly file system stuff

**Comment by zaibacu** [comment]
Just a heads up: this concrete bug is already fixed, however there were some backwards-incompatible changes done in AcceleratedText project, so will need some more time to adapt to current version
